extends: airbnb-base
plugins:
  - import
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
globals:
  __: true
  describe: true
  it: true
  td: true
  expect: true
  beforeEach: true
  afterEach: true
